### PR TITLE
chore(build): paused semantic release

### PR DESCRIPTION
**Pull request by sarbbottam**
and refactored .travis.yml

### CODE REVIEW

**Comment by ta2edchimp** [comment]
:+1:

But I guess, renaming the other PR would have been sufficient :stuck_out_tongue_winking_eye:

**Comment by sarbbottam** [comment]
>But I guess, renaming the other PR would have been sufficient

I guess not, searched it before suggesting this step http://stackoverflow.com/questions/20007578/renaming-a-branch-while-on-pull-request

**Comment by ta2edchimp** [comment]
Meh, I misinderstood you then. I thought of renaming the PR, not the branch m(

**Comment by ta2edchimp** [comment]
Aaaah... I think *this* would be a good case for the "Squash and Merge" feature. Would have been a single commit then, without the additional "Merged #n from branch-name" entry in the commit history.

**Comment by sarbbottam** [comment]
>> Merge pull request #4 from sarbbottam/no-semantic-release

screen shot 2016-04-08 at 12 51 09 am

It might sound silly, just wanted to avoid a typo from commit history

**Comment by sarbbottam** [comment]
>Would have been a single commit then, without the additional "Merged #n from branch-name" entry in the commit history.

Oops didn't realize it, will use this feature on next PR, hate to see this `"Merged #n from branch-name" `

**Comment by ta2edchimp** [comment]
Yeah, I didn't really get what that new feature does until I tried it in another repo of mine and was like "whoa, this is what I always wanted"... At least for some PRs.

**Pull request merged**
